// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT80xMxgzIK_z3NyJLpSP8ae0nB97kOu0',
    appId: '1:240493946576:web:1cff45c797549f22f9e0d5',
    messagingSenderId: '240493946576',
    projectId: 'yargidmobile',
    authDomain: 'yargidmobile.firebaseapp.com',
    storageBucket: 'yargidmobile.appspot.com',
    measurementId: 'G-0MGPHKGXP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaFf9dJJusVl6dOwoQMvRxzo4Jsd65dfQ',
    appId: '1:240493946576:android:75f2fb4057d95049f9e0d5',
    messagingSenderId: '240493946576',
    projectId: 'yargidmobile',
    storageBucket: 'yargidmobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl9OKjO98AmpVbeEb9eEMNYKl6vFwFmo4',
    appId: '1:240493946576:ios:471445335ddafca7f9e0d5',
    messagingSenderId: '240493946576',
    projectId: 'yargidmobile',
    storageBucket: 'yargidmobile.appspot.com',
    androidClientId: '240493946576-c0sqsuhckqu1bp4dfvrf3e657dhi591l.apps.googleusercontent.com',
    iosClientId: '240493946576-kr66p372n927v2f141g8n65ftt9hc7f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.yarGidMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl9OKjO98AmpVbeEb9eEMNYKl6vFwFmo4',
    appId: '1:240493946576:ios:2fdbae809a5b3367f9e0d5',
    messagingSenderId: '240493946576',
    projectId: 'yargidmobile',
    storageBucket: 'yargidmobile.appspot.com',
    androidClientId: '240493946576-c0sqsuhckqu1bp4dfvrf3e657dhi591l.apps.googleusercontent.com',
    iosClientId: '240493946576-2n5npkp5bctcn1rs47d0rgfpeir3lnga.apps.googleusercontent.com',
    iosBundleId: 'com.example.yarGidMobile.RunnerTests',
  );
}
